export const ADD_ITEM_TO_CART = 'ADD_ITEM_TO_CART';
export const REMOVE_ITEM_FROM_CART = 'REMOVE_ITEM_FROM_CART';
export const TOGGLE_CURRENCY = 'TOGGLE_CURRENCY';
export const TOGGLE_MODAL_IS_OPEN = 'SET_MODAL_IS_OPEN';
export const SET_ORDER = 'SET_ORDER';
export const SET_USER = 'SET_USER';
